### ISSUE TITLE
特定の条件下で、トライデントで保護領域内のMob&プレイヤーに攻撃できる

### ISSUE THREAD

**Issue by nekotion** [GravittoGroup/MCPlayNetwork-issue#23]
天候が雷雨の状態で、召雷エンチャントを付与したトライデントでの攻撃により、他プレイヤーの保護領域内であっても一部友好Mobやプレイヤーが雷によるダメージを受ける。

**Comment by snake0053** [comment]
2019年4月10日のアップデートにて修正しました。
ご報告ありがとうございました。

2019/04/10 - アップデートログ
https://community.mcplay.biz/thread-83.html
